### PR TITLE
upgrade k8s/client-go to 2.0.0

### PR DESCRIPTION
**Pull request by joemiller**

### CODE REVIEW

**Comment by roboll** [comment]
Love that this is net negative, the new client deps are much lighter. Thanks a lot for doing this! 🎉

**Comment by joemiller** [comment]
@roboll I'm having issues building it now, although my local build from a couple weeks ago was fine. I will try to fix and send a new PR. Apologies. I blame the state of go vendor/dep management =)

**Comment by roboll** [comment]
Yeah there's something odd going on, I can't seem to get one lib vendored because of an error with launchpad.net. Not sure what's going on, but I'll try to resolve it tomorrow if you dont figure something out.

**Comment by joemiller** [comment]
@roboll I just pulled your latest master commit and I am able to build again, but it could be due to the correct files being in my $GOPATH. I also had very inconsistent behavior when I was trying to reset the vendor dir a moment ago.

I think I'll try to pull your current master branch into a 'clean/empty' go 1.8.1 docker environment and try to compile there. If that works, then I think we can say the vendor tree is "good" now.

**Comment by joemiller** [comment]
I'm getting closer but now having an issue with k8s/client-go's dependency on github.com/emicklei/go-restful/swagger  which looks like it may have re-arranged themselves in a broken way and since govendor is pulling master it's not grabbing a version compatible with the k8s/client-go. *sigh*.  I'll keep plugging away at it though.

**Pull request merged**
