### PR TITLE
use go dep for dependency management, and update to kube client-go 2.0.0

### PR DESCRIPTION
**Pull request by joemiller**
changes in this PR:

- We're very interested in using this at my day job. We have a few changes in mind that are works in progress. At least one of them requires a newer version of kube's client-go lib (the `2.0.0` branch). This PR drops the previous `./vendor` dir entirely and replaces it with one managed by `dep` instead (`manifest.json` and `lock.json` also added to the repo).
- Added a simple `make deps` task to run `deps ensure`. I have not used dep much yet but I think this should be sufficient for bootstrapping a new dev or CI environment.

### CODE REVIEW

**Comment by joemiller** [comment]
@roboll This project is just what we're looking for! We have some changes we'd like to implement and we're working on those now. I am wondering what the status of this project is. It seems like there has not been a lot of updates since the initial commit.

**Comment by roboll** [comment]
Hey - glad to hear the project looks interesting to you 😄 . I haven't been using it actively lately, so like you said, not much activity. 

I'd definitely like to see the project develop - assuming your changes are in line with what I was thinking, I'd be open to granting you or others from your org committer access. Feel free to open issues here or shoot me an email at robertcboll at gmail dot com if you'd like to discuss further.

I'll review this PR in more detail tomorrow. Thanks!

**Comment by roboll** [comment]
@joemiller sorry to leave this longer than expected. I played with dep and wasn't quite convinced it was ready for action, and they still call it alpha. Have you been using it successfully? I sort of lean toward sticking with a proven solution unless there's a strong reason to move over before the tool is complete.

**Comment by joemiller** [comment]
I have been using it with a couple kube related projects lately and has
been working well. I'm not certain about this but it seems like it also
might be the only sane way to work with the k8s.io/client-go lib, which has
been undergoing so much change and seems to have landed on using git tags
for versioning.

In the case of kube-vault-controller, there was nothing doing the dep
management already, and I needed to bump the version of k8s/client-go in
order to add Event recording features. The recommended way in client-go was
to use dep.

My intent was to followup this PR with a PR that adds event recording to
the vault-controller. This is quite helpful with providing feedback to the
users. For example, it's easy to push a bad secretClaim that can't be
satisfied, but in order to view the logs one would need to run kubectl-logs
on the vault-controller in the kube-system namespace. For our engineers we
want them to be able to `kubectl describe secretclaim foo` and see the log
message for failure.

**Comment by joemiller** [comment]
@roboll With that said, you're right, it's alpha/beta/whatever. And in fact I need to update this PR. They recently switched from the manifest.json+lock.json to Gopkg.toml + Gopkg.lock =)

I had to put down working on vault-controller for about a week to work on another kube controller (which I used this project as the base for - thank you!). I had to upgrade and convert from the manifest/lock.json to the Gopkg.toml in the middle of that project too but it was super easy.

**Comment by roboll** [comment]
> In the case of kube-vault-controller, there was nothing doing the dep
management already, and I needed to bump the version of k8s/client-go in
order to add Event recording features. The recommended way in client-go was
to use dep.

This project does use a vendoring tool - `govendor` - https://github.com/kardianos/govendor. You should be able to update the dependency using that. I know it's not documented, I should put that in the README.

> My intent was to followup this PR with a PR that adds event recording to
the vault-controller. This is quite helpful with providing feedback to the
users. For example, it's easy to push a bad secretClaim that can't be
satisfied, but in order to view the logs one would need to run kubectl-logs
on the vault-controller in the kube-system namespace. For our engineers we
want them to be able to `kubectl describe secretclaim foo` and see the log
message for failure.

Love the idea. Looking forward to the PR.

> I had to put down working on vault-controller for about a week to work on another kube controller (which I used this project as the base for - thank you!).

Glad I could help. 😄

**Comment by joemiller** [comment]
Ah! I have not used govendor, I didn't know it was using it.

When I have some more time I'll try to re-work this PR to use govendor to
update the k8s/client-go dep instead, and then I'll send the other PR for
the MVP of the event-recording.

**Comment by joemiller** [comment]
@roboll I am trying to update the k8s.io/client-go lib with govendor but I've never used the tool before and not sure on the right approach. My first attempt was 
```
govendor fetch k8s.io/client-go@v2
```
 which seemed like it might be similar to k8s' recommendation with dep 
```
dep ensure k8s.io/client-go@^2.0.0
```
from https://github.com/kubernetes/client-go/blob/master/INSTALL.md#dep. This added a new import to the vendor/vendor.json but all of the old `k8s.io/client-go/1.5/` remained in the vendor.json. Any suggestions or hints are appreciated! thanks.

**Comment by joemiller** [comment]
@roboll I made a little bit of progress. I discovered that the proper command to pull down the whole k8s dep should be (i think....):
```
govendor fetch k8s.io/client-go/...@v2
```

I tried this on the existing codebase but I have compilation failures and much of them seem related to old bits from k8s.io/client-go/1.5 hanging around.

Trying a different approach - wiping `vendor`, re-initing and then fetching the 2.0.0 k8s.io/client-go yielded much better results - a successful build.

Thoughts on just wiping vendor and re-initing with govendor? I can send a new PR with this work.

**Comment by roboll** [comment]
Hey @joemiller, sorry it's taken me a while to get back to you. I haven't had to remove a vendor dependency using govendor before, so I don't know what the best approach is. If you can't figure something out, then wiping `vendor` and re-initing should be fine. 
```
rm -rf vendor/
govendor init
govendor add +e
```

Let me know if this doesn't work out for you, and I can try to take a pass at it.

**Comment by joemiller** [comment]
I have a branch where I did exactly that. I've had to put this down and
work on other things but intend to come back to it soon! thanks

**Comment by joemiller** [comment]
@roboll https://github.com/roboll/kube-vault-controller/pull/2

I suggest we close & delete this branch and consider #2 instead.

**Pull request closed without merging**
