### PR TITLE
add missing deps to vendor

### PR DESCRIPTION
**Pull request by joemiller**
With this I am able to build again, within a "clean" go 1.8.1 environment.

Here's what I did:

Iterated on the build until it succeeded using the official go 1.8.1 container for the clean environment:
```
docker run --rm -v "$PWD":/go/src/github.com/roboll/kube-vault-controller -w /go/src/github.com/roboll/kube-vault-controller -it golang:1.8.1 make build
```

I ended up with the following commands being sufficient to fix the issue with missing deps:
```
govendor fetch github.com/hashicorp/vault/api
govendor fetch github.com/emicklei/go-restful/swagger@v1.2
```

Verified the newly built artifact
```
$ file kube-vault-controller
kube-vault-controller: ELF 64-bit LSB executable, x86-64, version 1 (SYSV), statically linked, not stripped
```

### CODE REVIEW

**Comment by roboll** [comment]
thanks so much for figuring this out!

**Comment by joemiller** [comment]
@roboll So, I can now build with `make build` from either my local env (macos) and from a clean go docker container. However I get issues with `go test` or `go run`, strangely. I also see these in my editor upon saving.

```
$ go test .
# github.com/roboll/kube-vault-controller/vendor/github.com/mailru/easyjson/jwriter
vendor/github.com/mailru/easyjson/jwriter/writer.go:48: too many arguments in call to w.Buffer.BuildBytes
        have ([][]byte...)
        want ()
vendor/github.com/mailru/easyjson/jwriter/writer.go:58: w.Buffer.ReadCloser undefined (type buffer.Buffer has no field or method ReadCloser)
# github.com/roboll/kube-vault-controller/vendor/golang.org/x/text/unicode/norm
vendor/golang.org/x/text/unicode/norm/normalize.go:277: undefined: transform.ErrEndOfSpan
vendor/golang.org/x/text/unicode/norm/normalize.go:291: undefined: transform.ErrEndOfSpan
```
```
$ go run main.go 
# github.com/roboll/kube-vault-controller/vendor/github.com/mailru/easyjson/jwriter
vendor/github.com/mailru/easyjson/jwriter/writer.go:48: too many arguments in call to w.Buffer.BuildBytes
        have ([][]byte...)
        want ()
vendor/github.com/mailru/easyjson/jwriter/writer.go:58: w.Buffer.ReadCloser undefined (type buffer.Buffer has no field or method ReadCloser)
# github.com/roboll/kube-vault-controller/vendor/golang.org/x/text/unicode/norm
vendor/golang.org/x/text/unicode/norm/normalize.go:277: undefined: transform.ErrEndOfSpan
vendor/golang.org/x/text/unicode/norm/normalize.go:291: undefined: transform.ErrEndOfSpan
```

I'm curious if you are seeing this too. I _think_ it may be something in my $GOPATH but not really sure yet. I have found some old vendor'd versions of mailru/easyjson with a Buffer.BuildBytes() func that really does take no arguments, but I'm not sure how/why they're being used by go rather than the correct BuildBytes() func in the vendor'd dir.

`go test .` works fine from a clean docker environment so it must be something in my $GOPATH somewhere:
```
$ docker run --rm -v "$PWD":/go/src/github.com/roboll/kube-vault-controller -w /go/src/github.com/roboll/kube-vault-controller -it golang:1.8.1 bash
root@2e2e6844cbc1:/go/src/github.com/roboll/kube-vault-controller# go test .
?       github.com/roboll/kube-vault-controller [no test files]
root@2e2e6844cbc1:/go/src/github.com/roboll/kube-vault-controller#
```

**Comment by joemiller** [comment]
I'm really at a loss here fighting with my GOPATH. I think i'm going to try dep again in case this is caused by some quirk of govendor.

**Comment by joemiller** [comment]
@roboll I am not blaming govendor specifically because I really don't understand what the problem is here. But I am able to move without friction if I switch to dep. Also I have not had to explicitly add some of k8s/client-go's dependencies when using dep like I had to do earlier in this PR with govendor (ie: adding the older go-restful/swagger pkg manually).  Perhaps dep has smarter logic with regards to handling dependencies of dependencies. I don't know.

I know that dep is alpha or beta but it seems likely to be the standard, and it is the documented way to vendor k8s/client-go with their new tag-based versioning rather than path-based versioning approach.

Thoughts again on switching to dep for this project?

Switched to dep and everything (test & build) work fine in my local $GOPATH as well as within a clean docker go env:
```
$ rm -rf vendor
$ dep init
Cached github.com/ugorji/go
Cached github.com/hashicorp/go-cleanhttp
Cached github.com/hashicorp/errwrap
Cached github.com/hashicorp/go-multierror
Cached github.com/fatih/structs
Cached github.com/mitchellh/mapstructure
Cached github.com/hashicorp/hcl
Cached k8s.io/client-go
Cached golang.org/x/net
Cached github.com/hashicorp/vault

$ dep ensure k8s.io/client-go@^2.0.0

$ go test -v .
?       github.com/roboll/kube-vault-controller [no test files]

$ docker run --rm -v "$PWD":/go/src/github.com/roboll/kube-vault-controller -w /go/src/github.com/roboll/kube-vault-controller -it golang:1.8.1 go test
-v .
?       github.com/roboll/kube-vault-controller [no test files]

$ docker run --rm -v "$PWD":/go/src/github.com/roboll/kube-vault-controller -w /go/src/github.com/roboll/kube-vault-controller -it golang:1.8.1 make build
GOOS=linux GOARCH=amd64 CGO_ENABLED=0 go build -a .
```

**Pull request merged**
